# Generated by Django 4.0.3 on 2022-07-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_nor_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
