# Generated by Django 4.0.3 on 2022-04-06 19:17

import campaign_statistics.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.TextField()),
                ('cover_image', models.ImageField(upload_to=campaign_statistics.models.campaign_cover_image_directory_path)),
                ('video_link', models.TextField()),
                ('campaign_detail_completed', models.BooleanField(default=False)),
                ('campaign_verification_success', models.BooleanField(default=False)),
                ('campaign_launch_date', models.DateTimeField(blank=True, null=True)),
                ('campaign_duration', models.DateTimeField(blank=True, null=True)),
                ('campaign_total_funded', models.DecimalField(decimal_places=2, max_digits=14)),
                ('campaign_goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campaign_currency', models.CharField(max_length=256)),
                ('campaign_project_description', models.TextField()),
                ('campaign_risk_challenges', models.TextField()),
                ('campaign_environment_commitment', models.TextField()),
                ('campaign_bank_account_no', models.CharField(max_length=256)),
                ('campaign_bank_account_ifsc', models.CharField(max_length=256)),
                ('campaign_age_range_min', models.IntegerField()),
                ('campaign_age_range_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=256)),
                ('item_quantity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_statistics.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_image', models.ImageField(upload_to=campaign_statistics.models.reward_image_directory_path)),
                ('reward_title', models.CharField(max_length=256)),
                ('reward_description', models.TextField()),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reward_isdigital', models.BooleanField(default=False)),
                ('reward_shipping', models.CharField(choices=[('1', 'Shipped through email'), ('2', 'Shipping restricted to certain countries'), ('3', 'Anywhere in the world')], default='3', max_length=256)),
                ('reward_estimated_delivery', models.DateField()),
                ('reward_quantity_is_unlimited', models.BooleanField(default=False)),
                ('reward_quantity', models.BigIntegerField()),
                ('reward_quantity_left', models.BigIntegerField()),
                ('associated_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_statistics.campaign')),
                ('items', models.ManyToManyField(blank=True, to='campaign_statistics.items')),
            ],
        ),
    ]
