# Generated by Django 4.0.3 on 2022-04-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_gender',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.gender'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_tags',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.tags'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='categorites',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.subcategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_statistics.country'),
        ),
    ]
