# Generated by Django 4.0.3 on 2022-07-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0003_campaign_nor_score_campaign_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='score',
        ),
    ]
