# Generated by Django 4.0.3 on 2022-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0004_remove_campaign_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_onlyphysical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_images',
            field=models.ManyToManyField(to='campaign_statistics.campaignimage'),
        ),
    ]
