# Generated by Django 4.0.3 on 2022-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0005_campaignimage_reward_reward_onlyphysical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
