# Generated by Django 4.0.3 on 2022-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0007_campaignimage_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='reward_estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_isdigital',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_onlyphysical',
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_estimated_delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.TextField(choices=[('Digital', 'Digital'), ('Physical', 'Physical'), ('Both', 'Both')], default='Both', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
