# Generated by Django 4.0.3 on 2022-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0008_remove_reward_reward_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='funding_distribution',
            field=models.JSONField(default={'none': None}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timelines',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.timeline'),
        ),
    ]
