# Generated by Django 4.0.3 on 2022-07-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0009_timeline_campaign_funding_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='campaign_statistics.campaign')),
                ('recommended_models', models.ManyToManyField(blank=True, related_name='recommended_to', to='campaign_statistics.campaign')),
            ],
        ),
    ]
