# Generated by Django 4.0.3 on 2022-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0012_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='score_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
