# Generated by Django 4.0.3 on 2022-07-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0014_reward_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_everywhere', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_statistics.country')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='shippings',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.shipping'),
        ),
    ]
