# Generated by Django 4.0.3 on 2022-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0015_remove_reward_user_shipping_reward_shippings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
