# Generated by Django 4.0.3 on 2022-07-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_statistics', '0013_campaign_score_ignore'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='campaign_statistics.campaign'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='campaign_statistics.reward'),
        ),
    ]
