# Generated by Django 4.0.3 on 2022-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('TXN_SUCCESS', 'TXN_SUCCESS'), ('TXN_FALIURE', 'TXN_FALIURE')], default='Pending', max_length=11),
        ),
    ]
