# Generated by Django 4.0.3 on 2022-05-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Valuation',
        ),
    ]
