# Generated by Django 4.0.3 on 2022-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolcategory_tools_is_deleted_tools_score_ignore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='category',
        ),
        migrations.AddField(
            model_name='tools',
            name='category',
            field=models.ManyToManyField(blank=True, to='tools.toolcategory'),
        ),
    ]
