# Generated by Django 4.0.3 on 2022-07-07 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tools_category_tools_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
