# Generated by Django 4.0.3 on 2022-07-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_tools_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tools.tools')),
                ('recommended_models', models.ManyToManyField(blank=True, related_name='recommended_to', to='tools.tools')),
            ],
        ),
    ]
